import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { useAdminCategories, useAdminProducts, useCreateProduct, useDeleteProduct, useUpdateProduct } from "@/hooks/useAdmin";
import { PageTitle } from "@/components/admin/AdminShell";

export const Route = createFileRoute("/admin/products")({ component: Products });

type Product = any;
function Products() {
  const { data, isLoading } = useAdminProducts(); const { data: categories=[] } = useAdminCategories();
  const create = useCreateProduct(); const update = useUpdateProduct(); const remove = useDeleteProduct();
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Product | null>(null); const [open, setOpen] = useState(false);
  const items: Product[] = (data?.items ?? []).filter((p: Product) => p.name?.toLowerCase().includes(search.toLowerCase()));
  const blank = { name:"", slug:"", description:"", category:"", price:"", compareAtPrice:"", stock:"", imageKey:"", featured:false, bestSeller:false };
  const [form, setForm] = useState<any>(blank);
  const startCreate = () => { setEditing(null); setForm(blank); setOpen(true); };
  const startEdit = (p: Product) => { setEditing(p); setForm({ ...p, category:p.category?._id || p.category, price:String(p.price??""), compareAtPrice:String(p.compareAtPrice??""), stock:String(p.stock??"") }); setOpen(true); };
  const save = async (e:any) => { e.preventDefault(); const payload={...form, price:Number(form.price), stock:Number(form.stock), compareAtPrice:form.compareAtPrice?Number(form.compareAtPrice):undefined}; try { if(editing) await update.mutateAsync({id:editing._id,data:payload}); else await create.mutateAsync(payload); toast.success(editing?"Product updated":"Product created"); setOpen(false); } catch(err:any){ toast.error(err?.response?.data?.message||"Could not save product"); } };
  const archive = async (id:string) => { if(!confirm("Archive this product from the storefront?")) return; try { await remove.mutateAsync(id); toast.success("Product archived"); } catch(err:any){ toast.error(err?.response?.data?.message||"Could not archive product"); } };
  return <><PageTitle title="Products" description="Create, edit and archive storefront products." action={<button onClick={startCreate} className="inline-flex items-center gap-2 rounded-xl bg-purple-600 px-4 py-3 text-sm font-bold text-white hover:bg-purple-700"><Plus className="size-4"/> Add product</button>} />
    <div className="mb-4 flex items-center gap-3 rounded-2xl border bg-white px-4 py-3"><Search className="size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products…" className="w-full bg-transparent text-sm outline-none"/></div>
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th className="px-5">Actions</th></tr></thead><tbody className="divide-y">{isLoading ? <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-400">Loading products…</td></tr> : items.map(p=><tr key={p._id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="font-semibold">{p.name}</div><div className="text-xs text-slate-400">/{p.slug}</div></td><td>{p.category?.name || "—"}</td><td>${Number(p.price).toLocaleString()}</td><td>{p.stock}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${p.isActive!==false ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{p.isActive!==false?"Active":"Archived"}</span></td><td className="px-5"><div className="flex gap-1"><button onClick={()=>startEdit(p)} className="rounded-lg p-2 hover:bg-purple-50 hover:text-purple-600"><Pencil className="size-4"/></button><button onClick={()=>archive(p._id)} className="rounded-lg p-2 hover:bg-red-50 hover:text-red-600"><Trash2 className="size-4"/></button></div></td></tr>)}</tbody></table></div></div>
    {open && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-xl font-bold">{editing?"Edit product":"Add product"}</h2><p className="text-sm text-slate-500">Fields map directly to the product API.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Name" value={form.name} onChange={(v:string)=>setForm({...form,name:v})}/><Field label="Slug" value={form.slug} onChange={(v:string)=>setForm({...form,slug:v})}/><Field label="Price" type="number" value={form.price} onChange={(v:string)=>setForm({...form,price:v})}/><Field label="Compare at price" type="number" value={form.compareAtPrice} onChange={(v:string)=>setForm({...form,compareAtPrice:v})}/><Field label="Stock" type="number" value={form.stock} onChange={(v:string)=>setForm({...form,stock:v})}/><label className="block"><span className="mb-2 block text-sm font-semibold">Category</span><select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"><option value="">Select category</option>{categories.map((c:any)=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><div className="sm:col-span-2"><Field label="Image key / URL" value={form.imageKey} onChange={(v:string)=>setForm({...form,imageKey:v})}/></div><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Description</span><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="w-full rounded-xl border px-3 py-2.5 outline-none focus:border-purple-500"/></label><div className="flex gap-5 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={!!form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><label className="flex items-center gap-2"><input type="checkbox" checked={!!form.bestSeller} onChange={e=>setForm({...form,bestSeller:e.target.checked})}/> Best seller</label></div></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={create.isPending||update.isPending} className="rounded-xl bg-purple-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{create.isPending||update.isPending?"Saving…":"Save product"}</button></div></form></div>}
  </>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><input required={label!=="Compare at price"} type={type} value={value??""} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border px-3 py-2.5 outline-none focus:border-purple-500"/></label>}
